name: FastLeafDecay
version: '1.1'
main: com.cavetale.fastleafdecay.FastLeafDecayPlugin
api-version: '1.20.5'
description: Speed up Leaf Decay
author: StarTux
maintainer: Diamondback88
website: https://cavetale.com
