name: FastLeafDecay
version: '1.2'
main: com.cavetale.fastleafdecay.FastLeafDecayPlugin
api-version: '1.21.5'
description: Speed up Leaf Decay
author: StarTux
maintainer: Diamondback88
website: https://cavetale.com
